[package]
name = "rgengine"
version = "0.1.0"
edition = "2024"

[dependencies]
spdlog-rs = {workspace = true}
bitmask-enum = {workspace = true}
glfw = {workspace = true}
paste = {workspace = true}
lazy_static = {workspace = true}
