[package]
name = "rgengine"
version = "0.1.0"
edition = "2024"

[dependencies]
spdlog-rs = { version = "0.4.1", features = ["source-location"] }
bitflags = "2.9.0" 
paste = "1.0.15"


glfw = "0.31.0"
imgui-opengl-renderer = "0.5.0"
gl = "0.14.0"
imgui = "0.1.0"
imgui-glfw-rs = "0.4"
